### ISSUE TITLE
Question: Is there a maximum temperature

### ISSUE THREAD

**Issue by adrianbear** [MaikStohn/UP3D#24]
Hi Maik,

Now that I can use other slic3rs..Are there a maximum temperatures I should keep under for the extruder and the bed (specifically on my UP Box)?

Thanks
Adrian

**Comment by MaikStohn** [comment]
Hi,

a heater is mostly limited by the power provided to it. The power supply, the electronics in up and the connection cables are not big enough to generate "to high temperatures" at all.
So even if you set bed temperature to 1000°C it will never reach it. The heated bed in UP-Mini for instance can not get hotter than 95°C at all. 

The extruder heater can produce higher temperatures (>300°C) which might damage the thermistor (used to check temperature). This we just don't know yet since it's unknown what kind of thermistor Tiertime used. 

So using <300°C for extrusion temperature should be safe.

Maik

**Comment by adrianbear** [comment]
Excellent, thanks @MaikStohn
